// GERADO por scripts/gen-color-meta.mjs a partir de src/lib/data/nzwrapColors.ts — não editar à mão.
export const nzwrapColorMeta: Record<string, { name: string; finish: string; hex: string }> = {
  'nzw201': { name: "NZWRAP FERRARI METALLIC RED", finish: "Sólido/Metálico Brilhante", hex: '#ab071c' },
  'nzw202': { name: "NZWRAP STUTTGART SPORT GREY", finish: "Metálico Fosco", hex: '#5c5f63' },
  'nzw203': { name: "NZWRAP ALPINE SPORT GREY", finish: "Sólido Brilhante", hex: '#4a4f54' },
  'nzw204': { name: "NZWRAP LUXURY BRITISH PINK", finish: "Sólido/Metálico Brilhante", hex: '#ffb6c1' },
  'nzw205': { name: "NZWRAP MYSTIC TEAL", finish: "Camaleão", hex: '#008080' },
  'nzw206': { name: "NZWRAP SWEET VIOLET LIQUID METAL", finish: "Metálico Brilhante", hex: '#8a2be2' },
  'nzw207': { name: "NZWRAP MILITARY GREEN OPAQUE", finish: "Sólido Brilhante", hex: '#4b5320' },
  'nzw208': { name: "NZWRAP DIAMOND CHAMPAGNE", finish: "Metálico Brilhante", hex: '#fad6a5' },
  'nzw209': { name: "NZWRAP ICEBERG BLUE", finish: "Sólido Brilhante", hex: '#71a6d2' },
  'nzw210': { name: "NZWRAP VIPER GREEN", finish: "Metálico Brilhante", hex: '#00ff00' },
  'nzw211': { name: "NZWRAP DIAMOND SILVER", finish: "Metálico Brilhante", hex: '#c0c0c0' },
  'nzw212': { name: "NZWRAP DIAMOND WHITE", finish: "Metálico Brilhante", hex: '#ffffff' },
  'nzw213': { name: "NZWRAP DIAMOND YELLOW", finish: "Metálico Brilhante", hex: '#ffff00' },
  'nzw214': { name: "NZWRAP MYTHIC SAGE", finish: "Camaleão", hex: '#9dc183' },
  'nzw215': { name: "NZWRAP MYTHIC PURPLE", finish: "Camaleão Brilhante", hex: '#800080' },
  'nzw216': { name: "NZWRAP PIANO BLACK GLOSS", finish: "Sólido Brilhante", hex: '#000000' },
  'nzw217': { name: "NZWRAP URBAN ASH GLOSS", finish: "Sólido Brilhante", hex: '#b2beb5' },
  'nzw218': { name: "NZWRAP SAFARI KHAKI", finish: "Sólido Brilhante", hex: '#c3b091' },
  'nzw219': { name: "NZWRAP CHROME FLUID BLUE", finish: "Metálico Brilhante", hex: '#4682b4' },
  'nzw220': { name: "NZWRAP SATIN PLUM", finish: "Sólido Fosco", hex: '#dda0dd' },
  'nzw221': { name: "NZWRAP QUICKSILVER METALLIC", finish: "Metálico Brilhante", hex: '#e5e4e2' },
  'nzw222': { name: "NZWRAP SPICY ORANGE METALLIC", finish: "Metálico Brilhante", hex: '#ff4500' },
  'nzw223': { name: "NZWRAP METALLIC ONYX PEARL", finish: "Metálico Acetinado", hex: '#353839' },
  'nzw224': { name: "NZWRAP TOKYO BLOSSOM PEARL", finish: "Metálico Acetinado", hex: '#ffb7c5' },
  'nzw225': { name: "NZWRAP COSMIC GREY PEARL", finish: "Metálico Acetinado", hex: '#8c92ac' },
  'nzw226': { name: "NZWRAP AQUA JEWEL PEARL", finish: "Metálico Acetinado", hex: '#0abab5' },
  'nzw227': { name: "NZWRAP SATURN WHITE PEARL", finish: "Metálico Acetinado", hex: '#f8f8ff' },
  'nzw228': { name: "NZWRAP PURE PEARL WHITE", finish: "Sólido Brilhante", hex: '#fcf6f5' },
  'nzw229': { name: "NZWRAP INTERLAGOS YELLOW", finish: "Sólido Brilhante", hex: '#f5d547' },
  'nzw230': { name: "NZWRAP GALAXY BLUE ALUMINIUM", finish: "Metálico Brilhante", hex: '#1034a6' },
};
